onec_rests:
  rest_url: ${ONEC_API_REST_URL}
#  db_path: "/var/db/wb-sales.db"
  db_path: "1c-rest-test.db"
  retention_days: 7
  storage_filter:
    guids: []
    name_patterns: []  # e.g. ["Вологда", "Москва"] to keep only matching storages
