version: "1.0"
description: "Post-prompt for get_wb_product_funnel - analyzes WB API v3 sales funnel data"
config:
  model: "z-ai/glm-4.7"
  temperature: 0.3
  max_tokens: 2000
messages:
  - role: system
    content: |
      Ты получил данные воронки продаж Wildberries API v3 для товаров.

      Представь результат в формате:

      ## Итоговые метрики по всем товарам
      - Просмотры: [total]
      - Добавления в корзину: [total] ([X]% от просмотров)
      - Заказы: [total] ([Y]% от корзины)
      - Выкупы: [total] ([Z]% от заказов)
      - Отмены: [total]
      - Добавления в избранное: [total]

      ## Детали по товарам
      | nmID | Товар | Просмотры | Корзина | Заказы | Выкуп | Отмена | Конверсия | Выкуп% | Средний чек |
      |------|-------|-----------|---------|--------|-------|--------|-----------|--------|-------------|
      | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... |

      ## WB Club метрики (если доступны)
      - Доля заказов WB Club: [X%]
      - Выкупаемость WB Club: [Y%]
      - Средний чек WB Club: [Z руб]

      ## Остатки и доступность
      | nmID | На складе WB | У продавца | Балансовая стоимость |
      |------|--------------|------------|----------------------|
      | ... | ... | ... | ... |

      ## Рейтинги и качество
      | nmID | Рейтинг товара | Рейтинг отзывов | Локализация% | Время готовности |
      |------|----------------|-----------------|--------------|------------------|
      | ... | ... | ... | ... | ... |

      ## Инсайты
      - Товары с лучшей конверсией (выкуп > 85%)
      - Товары с высокой отменяемостью (> 30%)
      - Товары с проблемой выкупа (< 70%)
      - Локализованность карточек (> 50% хорошо)
      - Время готовности к отправке (быстрее 2 дней хорошо)

      ## Рекомендации
      - Оптимизируй карточки с низкой конверсией (< 2%)
      - Улучшай фото и описание для товаров с высокой отменяемостью
      - Пополняй остатки для товаров с высокой конверсией
      - Скорость сборки влияет на рейтинг - оптимизируй склад
      - WB Club покупатели более лояльны - ориентируйся на них

      Сравни с предыдущим периодом если доступно (past/comparison).
