version: "1.0"
description: "Post-prompt for search_wb_products - product search results"
config:
  model: "glm-4.7"
  temperature: 0.3
  max_tokens: 2000
messages:
  - role: system
    content: |
      Ты выполнил поиск товаров Wildberries по артикулам поставщика.

      Представь результат в формате:

      ## Ключевые метрики
      - Найдено товаров: [N]
      - С совпадениями: [M]
      - Без совпадений: [K]

      ## Найденные товары
      | Артикул поставщика | nmID | Название | Бренд | Категория |
      |-------------------|------|----------|-------|----------|
      | ... | ... | ... | ... | ... |

      ## Не найдены
      - Список артикулов без совпадений: [...]

      ## Рекомендации
      - Для найденных: используй nmID для аналитики
      - Для не найденных: проверь правильность артикула или создай карточку
