// db.go — read certificate data from onec_goods table (read-only).
package main

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/ilkoid/poncho-ai/pkg/filter"
	_ "github.com/mattn/go-sqlite3"
)

// CertRecord — certificate data from onec_goods.
type CertRecord struct {
	Article           string // vendor code (артикул)
	GoodName          string // product name
	CertificateType   string // "Сертификат соответствия" or "Декларация о соответствии"
	CertificateNumber string // e.g. "ЕАЭС RU С-CN.ПФ02.В.07011/23"
	LocalBegin        string // registration date from 1C (ISO)
	LocalEnd          string // expiration date from 1C (ISO)
	OneCType          string // 1C type: Обувь/Одежда/Аксессуары
	OneCCategory      string // 1C category level 1 name (читаемое название)
	WBSubject         string // WB subject name (предмет, читаемое название)
}

// loadCertificates reads certificate records from onec_goods (read-only).
// Applies filter.Filter criteria (vendor codes, years, subject, stock, 1C categories).
func loadCertificates(ctx context.Context, dbPath string, limit int, f filter.Filter) ([]CertRecord, error) {
	db, err := sql.Open("sqlite3", fmt.Sprintf("file:%s?mode=ro&_busy_timeout=5000", dbPath))
	if err != nil {
		return nil, fmt.Errorf("open db: %w", err)
	}
	defer db.Close()

	// Base query: onec_goods joined with cards for filter support.
	query := `
			SELECT og.article,
			       og.name,
			       og.certificate,
			       og.certificate_number,
			       og.certificate_begin,
			       og.certificate_end,
			       COALESCE(og.type, ''),
			       COALESCE(og.category_level1_name, ''),
			       COALESCE(c.subject_name, '')
			FROM onec_goods og
			JOIN cards c ON c.vendor_code = og.article
			WHERE og.has_certificate = 1
			  AND og.certificate_number IS NOT NULL
			  AND og.certificate_number != ''`

	var args []any

	// Apply filter.Filter via BuildSQL.
	if !f.Empty() {
		sqlResult, err := f.BuildSQL(filter.SQLConfig{CardsAlias: "c"})
		if err != nil {
			return nil, fmt.Errorf("build filter SQL: %w", err)
		}
		if sqlResult.Where != "" {
			query += " AND " + sqlResult.Where
			args = append(args, sqlResult.Args...)
		}
		// Add JOINs generated by filter (e.g., onec_goods alias "o" for 1C filters).
		for _, join := range sqlResult.JOINs {
			// Skip duplicate JOIN on onec_goods (we already have "og").
			if strings.Contains(join, "onec_goods") {
				// Rewrite "o." references to "og." in WHERE conditions.
				query = strings.ReplaceAll(query, " o.", " og.")
				continue
			}
			query = join + " " + query // prepend JOIN
		}
	}

	query += " ORDER BY og.certificate_number, og.article"

	if limit > 0 {
		query += fmt.Sprintf(" LIMIT %d", limit)
	}

	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("query onec_goods: %w", err)
	}
	defer rows.Close()

	var certs []CertRecord
	for rows.Next() {
		var c CertRecord
		if err := rows.Scan(
			&c.Article, &c.GoodName, &c.CertificateType,
			&c.CertificateNumber, &c.LocalBegin, &c.LocalEnd,
			&c.OneCType, &c.OneCCategory, &c.WBSubject,
		); err != nil {
			return nil, fmt.Errorf("scan: %w", err)
		}
		certs = append(certs, c)
	}
	return certs, rows.Err()
}
