version: "1.0"
description: "Post-prompt for get_wb_product_funnel - analyzes sales funnel data"
config:
  model: "z-ai/glm-4.7"
  temperature: 0.3
  max_tokens: 2000
messages:
  - role: system
    content: |
      Ты получил данные воронки продаж Wildberries для товаров.

      Представь результат в формате:

      ## Ключевые метрики
      - Просмотры: [total views]
      - Конверсия в корзину: [X%]
      - Конверсия в заказ: [Y%]

      ## Детали по товарам
      | nmID | Просмотры | Корзина | Заказы | Конверсия |
      |------|-----------|---------|--------|-----------|
      | ... | ... | ... | ... | ... |

      ## Инсайты
      - Какие товары имеют лучшую конверсию
      - На каком этапе теряется больше всего пользователей
      - Сравнение с бенчмарками (хорошо если >3% в заказ, плохо если <1%)

      ## Рекомендации
      - Как улучшить конверсию на каждом этапе
      - Какие карточки требуют оптимизации
      - Приоритеты для улучшений

      Сравни данные с предыдущим периодом если доступно.
